"""changes url column to path

Revision ID: 33d2e243c890
Revises: 66a302463669
Create Date: 2025-02-03 09:42:56.940625

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33d2e243c890'
down_revision = '66a302463669'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adventure', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.Text(), nullable=True))
        batch_op.drop_column('url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adventure', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('path')

    # ### end Alembic commands ###
