"""added models Content and Blog

Revision ID: 556e041e1561
Revises: 33d2e243c890
Create Date: 2025-02-03 16:09:43.905550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '556e041e1561'
down_revision = '33d2e243c890'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('publication_date', sa.DateTime(), nullable=True),
    sa.Column('adventure_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['adventure_id'], ['adventure.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('figure', sa.LargeBinary(), nullable=True),
    sa.Column('caption', sa.String(), nullable=True),
    sa.Column('blog_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blog_id'], ['blog.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('adventure', schema=None) as batch_op:
        batch_op.drop_column('path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adventure', schema=None) as batch_op:
        batch_op.add_column(sa.Column('path', sa.TEXT(), autoincrement=False, nullable=True))

    op.drop_table('content')
    op.drop_table('blog')
    # ### end Alembic commands ###
