"""add public column to Adventure model

Revision ID: 66a302463669
Revises: 0a6bb3d3eadc
Create Date: 2025-01-23 16:38:13.335700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66a302463669'
down_revision = '0a6bb3d3eadc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adventure', schema=None) as batch_op:
        batch_op.add_column(sa.Column('public', sa.Boolean(), nullable=True))
        batch_op.alter_column('url',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adventure', schema=None) as batch_op:
        batch_op.alter_column('url',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('public')

    # ### end Alembic commands ###
