"""adds alt_name to Adventure and Blog models

Revision ID: 7d1a18db19f0
Revises: eae20f72bb01
Create Date: 2025-03-08 12:44:56.243336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d1a18db19f0'
down_revision = 'eae20f72bb01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adventure', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alt_name', sa.String(), nullable=True))
        batch_op.create_unique_constraint(None, ['alt_name'])

    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alt_name', sa.String(), nullable=True))
        batch_op.create_foreign_key(None, 'adventure', ['alt_name'], ['alt_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('alt_name')

    with op.batch_alter_table('adventure', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('alt_name')

    # ### end Alembic commands ###
