"""removes alt_name from Blog and corrects relationship definition

Revision ID: d03b307506ce
Revises: 7d1a18db19f0
Create Date: 2025-03-08 13:57:50.065055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd03b307506ce'
down_revision = '7d1a18db19f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.drop_constraint('blog_alt_name_fkey', type_='foreignkey')
        batch_op.drop_column('alt_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alt_name', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('blog_alt_name_fkey', 'adventure', ['alt_name'], ['alt_name'])

    # ### end Alembic commands ###
